#!/bin/sh

if [ "$#" -ne 1 ]; then
    echo "usage ./cmd target-path"
    exit -1
fi

CURRENTDIR=$PWD
cd $1
find . -maxdepth 1 -type l | while read i;
do qualifies=$(file $i | sed -e "s/.*\`\(.*\)'/\1/g" | grep ^/lib)
if [ -n "$qualifies" ]; then
newPath=$(file $i | sed -e "s/.*\`\(.*\)'/\1/g" | sed -e "s,\`,,g" | sed -e "s,',,g" | sed -e 's,^/lib,../../lib,g');
echo $i
echo $newPath;
sudo rm $i;
sudo ln -s $newPath $i;
fi
done
cd $CURRENTDIR
